; Generated by scan-to-cnc
; Date: 2026-04-08T00:53:13.158430

G21 ; mm mode
G90 ; absolute positioning
G94 ; feed per minute

M3 S10000 ; spindle on
G4 P2 ; dwell for spindle
G0 Z10.000
; Pass 1
G0 X-0.299 Y-0.188
G1 Z0.371 F100
G1 F500
G1 X0.701
G0 Z10.000

; Pass 2
G0 Y1.812
G1 Z0.371 F100
G1 F500
G1 X-0.299
G0 Z10.000


M5 ; spindle off
G0 Z10 ; retract
G0 X0 Y0 ; return to origin
M30 ; program end