"""
G-code Writer Module

Converts toolpaths to G-code for GRBL and other controllers.
"""

import logging
from typing import List, TextIO
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# Import from sibling package
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from processing.toolpath import ToolpathPoint


@dataclass
class GcodeConfig:
    feed_rate: float = 500      # mm/min for cutting
    plunge_rate: float = 100    # mm/min for Z plunges
    rapid_rate: float = 1000    # mm/min (GRBL ignores, but useful for simulation)
    spindle_speed: int = 10000  # RPM
    coolant: bool = False
    dialect: str = 'grbl'       # 'grbl', 'linuxcnc', 'generic'
    
    # Precision
    decimal_places: int = 3
    

class GcodeWriter:
    """Generates G-code from toolpaths."""
    
    def __init__(self, config: GcodeConfig = None):
        self.config = config or GcodeConfig()
        self.lines: List[str] = []
        self._last_x = None
        self._last_y = None
        self._last_z = None
        self._last_feed = None
        
    def _fmt(self, value: float) -> str:
        """Format coordinate value."""
        return f"{value:.{self.config.decimal_places}f}"
        
    def _emit(self, line: str):
        """Add a line to output."""
        self.lines.append(line)
        
    def _move(self, cmd: str, x: float = None, y: float = None, 
              z: float = None, f: float = None):
        """Emit a move command with optional coordinates."""
        parts = [cmd]
        
        if x is not None and x != self._last_x:
            parts.append(f"X{self._fmt(x)}")
            self._last_x = x
        if y is not None and y != self._last_y:
            parts.append(f"Y{self._fmt(y)}")
            self._last_y = y
        if z is not None and z != self._last_z:
            parts.append(f"Z{self._fmt(z)}")
            self._last_z = z
        if f is not None and f != self._last_feed:
            parts.append(f"F{f:.0f}")
            self._last_feed = f
            
        if len(parts) > 1:  # Only emit if there's actual movement
            self._emit(' '.join(parts))
            
    def header(self, comment: str = None):
        """Write G-code header."""
        self._emit(f"; Generated by scan-to-cnc")
        self._emit(f"; Date: {datetime.now().isoformat()}")
        if comment:
            self._emit(f"; {comment}")
        self._emit("")
        
        # Setup commands
        if self.config.dialect == 'grbl':
            self._emit("G21 ; mm mode")
            self._emit("G90 ; absolute positioning")
            self._emit("G94 ; feed per minute")
        else:
            self._emit("G21")
            self._emit("G90")
            self._emit("G94")
            
        self._emit("")
        
    def start_spindle(self):
        """Spindle on command."""
        self._emit(f"M3 S{self.config.spindle_speed} ; spindle on")
        if self.config.dialect == 'grbl':
            self._emit("G4 P2 ; dwell for spindle")
            
    def stop_spindle(self):
        """Spindle off command."""
        self._emit("M5 ; spindle off")
        
    def coolant_on(self):
        """Enable coolant."""
        if self.config.coolant:
            self._emit("M8 ; coolant on")
            
    def coolant_off(self):
        """Disable coolant."""
        if self.config.coolant:
            self._emit("M9 ; coolant off")
            
    def rapid(self, x: float = None, y: float = None, z: float = None):
        """Rapid positioning move."""
        self._move("G0", x=x, y=y, z=z)
        
    def linear(self, x: float = None, y: float = None, z: float = None,
               feed: float = None):
        """Linear interpolation move."""
        f = feed or self.config.feed_rate
        self._move("G1", x=x, y=y, z=z, f=f)
        
    def plunge(self, z: float):
        """Plunge move at plunge feed rate."""
        self.linear(z=z, feed=self.config.plunge_rate)
        
    def footer(self):
        """Write G-code footer."""
        self._emit("")
        self.stop_spindle()
        self.coolant_off()
        self._emit("G0 Z10 ; retract")
        self._emit("G0 X0 Y0 ; return to origin")
        
        if self.config.dialect == 'grbl':
            self._emit("M30 ; program end")
        else:
            self._emit("M2")
            
    def from_toolpath(self, passes: List[List[ToolpathPoint]], 
                      clearance_z: float = 10.0):
        """
        Convert toolpath passes to G-code.
        
        Args:
            passes: List of toolpath passes from ToolpathGenerator
            clearance_z: Safe Z height for rapids
        """
        self.header()
        self.start_spindle()
        self.coolant_on()
        
        # Initial safe position
        self.rapid(z=clearance_z)
        
        for i, pass_points in enumerate(passes):
            if not pass_points:
                continue
                
            self._emit(f"; Pass {i+1}")
            
            for pt in pass_points:
                if pt.feed_type == 'rapid':
                    self.rapid(x=pt.x, y=pt.y, z=pt.z)
                elif pt.feed_type == 'plunge':
                    self.plunge(z=pt.z)
                else:  # cut
                    self.linear(x=pt.x, y=pt.y, z=pt.z)
                    
            # Retract after pass
            self.rapid(z=clearance_z)
            self._emit("")
            
        self.footer()
        
    def get_gcode(self) -> str:
        """Get complete G-code as string."""
        return '\n'.join(self.lines)
        
    def save(self, path: str):
        """Save G-code to file."""
        with open(path, 'w') as f:
            f.write(self.get_gcode())
        logger.info(f"Saved G-code to {path}: {len(self.lines)} lines")
        
    def estimate_time(self) -> float:
        """
        Estimate machining time in minutes.
        
        Rough estimate based on feed rates and distances.
        """
        total_time = 0.0
        last_pos = [0.0, 0.0, 0.0]
        
        for line in self.lines:
            if line.startswith('G0') or line.startswith('G1'):
                # Parse coordinates
                x, y, z = last_pos
                feed = self.config.rapid_rate if line.startswith('G0') else self.config.feed_rate
                
                for part in line.split():
                    if part.startswith('X'):
                        x = float(part[1:])
                    elif part.startswith('Y'):
                        y = float(part[1:])
                    elif part.startswith('Z'):
                        z = float(part[1:])
                    elif part.startswith('F'):
                        feed = float(part[1:])
                        
                # Calculate distance
                dx = x - last_pos[0]
                dy = y - last_pos[1]
                dz = z - last_pos[2]
                dist = (dx**2 + dy**2 + dz**2) ** 0.5
                
                total_time += dist / feed
                last_pos = [x, y, z]
                
        return total_time
        
    def clear(self):
        """Clear generated G-code."""
        self.lines = []
        self._last_x = None
        self._last_y = None
        self._last_z = None
        self._last_feed = None