"""
G-code Writer Module

Converts toolpaths to G-code for GRBL and other controllers.
"""

import logging
import math
from typing import List, TextIO
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# Import from sibling package
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from processing.toolpath import ToolpathPoint


@dataclass
class GcodeConfig:
    feed_rate: float = 500      # mm/min for cutting
    plunge_rate: float = 100    # mm/min for Z plunges
    rapid_rate: float = 1000    # mm/min (GRBL ignores, but useful for simulation)
    spindle_speed: int = 10000  # RPM
    coolant: bool = False
    dialect: str = 'grbl'       # 'grbl', 'linuxcnc', 'generic'

    # safety
    max_cut_depth: float = 50.0  # mm, abs value; cuts deeper than this get flagged

    # Precision
    decimal_places: int = 3


class GcodeWriter:
    """Generates G-code from toolpaths."""

    def __init__(self, config: GcodeConfig = None):
        self.config = config or GcodeConfig()
        self.lines: List[str] = []
        self._last_x = None
        self._last_y = None
        self._last_z = None
        self._last_feed = None

    def _fmt(self, value: float) -> str:
        """Format coordinate value."""
        return f"{value:.{self.config.decimal_places}f}"

    def _emit(self, line: str):
        """Add a line to output."""
        self.lines.append(line)

    def _move(self, cmd: str, x: float = None, y: float = None,
              z: float = None, f: float = None):
        """Emit a move command with optional coordinates."""
        parts = [cmd]

        if x is not None and x != self._last_x:
            parts.append(f"X{self._fmt(x)}")
            self._last_x = x
        if y is not None and y != self._last_y:
            parts.append(f"Y{self._fmt(y)}")
            self._last_y = y
        if z is not None and z != self._last_z:
            parts.append(f"Z{self._fmt(z)}")
            self._last_z = z
        if f is not None and f != self._last_feed:
            parts.append(f"F{f:.0f}")
            self._last_feed = f

        if len(parts) > 1:  # only emit if there's actual movement
            self._emit(' '.join(parts))

    def header(self, comment: str = None):
        """Write G-code header."""
        self._emit(f"; Generated by scan-to-cnc")
        self._emit(f"; Date: {datetime.now().isoformat()}")
        if comment:
            self._emit(f"; {comment}")
        self._emit("; zero machine on top-front-left corner of stock before running")
        self._emit("")

        if self.config.dialect == 'grbl':
            self._emit("G21 ; mm mode")
            self._emit("G90 ; absolute positioning")
            self._emit("G94 ; feed per minute")
            self._emit("G17 ; XY plane")
            self._emit("G54 ; work coordinate system 1")
        else:
            self._emit("G21")
            self._emit("G90")
            self._emit("G94")

        self._emit("")

    def start_spindle(self):
        """Spindle on command."""
        self._emit(f"M3 S{self.config.spindle_speed} ; spindle on")
        if self.config.dialect == 'grbl':
            self._emit("G4 P2 ; dwell for spindle")

    def stop_spindle(self):
        """Spindle off command."""
        self._emit("M5 ; spindle off")

    def coolant_on(self):
        """Enable coolant."""
        if self.config.coolant:
            self._emit("M8 ; coolant on")

    def coolant_off(self):
        """Disable coolant."""
        if self.config.coolant:
            self._emit("M9 ; coolant off")

    def rapid(self, x: float = None, y: float = None, z: float = None):
        """Rapid positioning move."""
        self._move("G0", x=x, y=y, z=z)

    def linear(self, x: float = None, y: float = None, z: float = None,
               feed: float = None):
        """Linear interpolation move."""
        f = feed or self.config.feed_rate
        self._move("G1", x=x, y=y, z=z, f=f)

    def plunge(self, z: float):
        """Plunge move at plunge feed rate."""
        self.linear(z=z, feed=self.config.plunge_rate)

    def footer(self):
        """Write G-code footer."""
        self._emit("")
        self.stop_spindle()
        self.coolant_off()
        self._emit("G0 Z10 ; retract")
        self._emit("G0 X0 Y0 ; return to origin")

        if self.config.dialect == 'grbl':
            self._emit("M30 ; program end")
        else:
            self._emit("M2")

    def _bounding_box_preview(self, passes: List[List[ToolpathPoint]],
                              clearance_z: float):
        """spindle-off rapid trace around the XY bounding box of all passes.
        lets the operator visually confirm stock is positioned correctly
        before cutting begins. pauses at the end for operator to resume."""
        xs = [pt.x for p in passes for pt in p]
        ys = [pt.y for p in passes for pt in p]
        if not xs or not ys:
            return

        x_min, x_max = min(xs), max(xs)
        y_min, y_max = min(ys), max(ys)

        self._emit("; --- bounding box preview (spindle off) ---")
        self._emit("; verify the bit traces the stock perimeter, then resume")
        self._emit(f"G0 Z{self._fmt(clearance_z)}")
        self._last_z = clearance_z
        self._emit(f"G0 X{self._fmt(x_min)} Y{self._fmt(y_min)}")
        self._emit(f"G0 X{self._fmt(x_max)} Y{self._fmt(y_min)}")
        self._emit(f"G0 X{self._fmt(x_max)} Y{self._fmt(y_max)}")
        self._emit(f"G0 X{self._fmt(x_min)} Y{self._fmt(y_max)}")
        self._emit(f"G0 X{self._fmt(x_min)} Y{self._fmt(y_min)}")
        self._emit("M0 ; pause - verify stock position, then resume in sender")
        self._last_x = x_min
        self._last_y = y_min
        self._emit("")

    def from_toolpath(self, passes: List[List[ToolpathPoint]],
                      clearance_z: float = 10.0,
                      preview: bool = True):
        """
        Convert toolpath passes to G-code.

        Assumes the operator has zeroed the machine on the top-front-left
        corner of the stock (X=0, Y=0, Z=0 at that point). When preview=True,
        the machine traces the bounding box with spindle off and pauses so
        the operator can verify the stock is in the right place before cutting.

        Args:
            passes: List of toolpath passes from ToolpathGenerator
            clearance_z: Safe Z height for rapids
            preview: If True, trace bounding box and pause before cutting
        """
        self.header()

        # safe start: retract first (in case bit is in stock), then move to
        # work zero above the stock.
        self._emit("; --- safe start sequence ---")
        self._emit("; assumes machine is zeroed on top-front-left of stock")
        self._emit(f"G0 Z{self._fmt(clearance_z)} ; retract to clearance")
        self._last_z = clearance_z
        self._emit("G0 X0 Y0 ; move to work zero (XY)")
        self._last_x = 0.0
        self._last_y = 0.0
        self._emit("")

        # bounding box preview before spindle starts
        if preview:
            self._bounding_box_preview(passes, clearance_z)

        self.start_spindle()
        self.coolant_on()

        # park above work zero, ready for first pass
        self.rapid(x=0.0, y=0.0, z=clearance_z)

        for i, pass_points in enumerate(passes):
            if not pass_points:
                continue

            self._emit(f"; Pass {i+1}")

            for pt in pass_points:
                # guard against invalid/dangerous Z values from upstream
                if pt.z is None or not math.isfinite(pt.z):
                    logger.warning(f"invalid Z at ({pt.x}, {pt.y}), retracting")
                    self.rapid(z=clearance_z)
                    continue
                if pt.z < -self.config.max_cut_depth:
                    logger.warning(f"Z={pt.z} exceeds max_cut_depth at "
                                   f"({pt.x}, {pt.y}), retracting")
                    self.rapid(z=clearance_z)
                    continue

                if pt.feed_type == 'rapid':
                    # always retract Z before XY rapid to avoid dragging
                    # through stock
                    if self._last_z is None or self._last_z < clearance_z:
                        self.rapid(z=clearance_z)
                    self.rapid(x=pt.x, y=pt.y, z=pt.z)
                elif pt.feed_type == 'plunge':
                    self.plunge(z=pt.z)
                else:  # cut
                    self.linear(x=pt.x, y=pt.y, z=pt.z)

            # retract after pass
            self.rapid(z=clearance_z)
            self._emit("")

        self.footer()

    def get_gcode(self) -> str:
        """Get complete G-code as string."""
        return '\n'.join(self.lines)

    def save(self, path: str):
        """Save G-code to file."""
        with open(path, 'w') as f:
            f.write(self.get_gcode())
        logger.info(f"Saved G-code to {path}: {len(self.lines)} lines")

    def estimate_time(self) -> float:
        """
        Estimate machining time in minutes.

        Rough estimate based on feed rates and distances.
        """
        total_time = 0.0
        last_pos = [0.0, 0.0, 0.0]

        for line in self.lines:
            if line.startswith('G0') or line.startswith('G1'):
                x, y, z = last_pos
                feed = self.config.rapid_rate if line.startswith('G0') else self.config.feed_rate

                for part in line.split():
                    if part.startswith('X'):
                        x = float(part[1:])
                    elif part.startswith('Y'):
                        y = float(part[1:])
                    elif part.startswith('Z'):
                        z = float(part[1:])
                    elif part.startswith('F'):
                        feed = float(part[1:])

                dx = x - last_pos[0]
                dy = y - last_pos[1]
                dz = z - last_pos[2]
                dist = (dx**2 + dy**2 + dz**2) ** 0.5

                if feed > 0:
                    total_time += dist / feed
                last_pos = [x, y, z]

        return total_time

    def clear(self):
        """Clear generated G-code."""
        self.lines = []
        self._last_x = None
        self._last_y = None
        self._last_z = None
        self._last_feed = None